name = "hello_world"
version = "1.0.0"
licences = ["Apache-2.0"]
repository = { type = "github", user = "patte", repo = "gleam-playground" }
links = [
    { title = "GitHub", href = "https://github.com/patte/gleam-playground" },
]
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.40.0 and < 1.0.0"
gleam_erlang = ">= 0.26.0 and < 1.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
gleam_otp = ">= 0.12.0 and < 1.0.0"
logging = ">= 1.3.0 and < 2.0.0"
mist = ">= 2.0.0 and < 3.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
glisten = ">= 5.0.0 and < 6.0.0"
birl = ">= 1.7.1 and < 2.0.0"
#radiate = ">= 0.4.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
